nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

plugins:
  # This is a VERY basic "E2E" test for the engines plugin.
  # It's not perfect since this repo doesn't cover a lot of peer dep scenarios.
  - path: ./plugins/engines/dist/plugin.dev.js
  # This one is a no-op
  - path: ./plugins/npmrc/dist/plugin.dev.js
