# The store layout prevents issues with different module layouts between local and CI
# causing failures due to changes in the dev bundles...
nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.17.1.cjs

npmMinimalAgeGate: 7d

enableScripts: false

plugins:
  # This is a VERY basic "E2E" test for the engines plugin.
  # It's not perfect since this repo doesn't cover a lot of peer dep scenarios.
  - path: ./plugins/engines/dist/plugin.dev.js
  # This one is a no-op
  - path: ./plugins/npmrc/dist/plugin.dev.js
