name: PR

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  # For PRs, use the ref (branch) in the concurrency group so that new pushes cancel any old runs.
  # For pushes to main, ideally we wouldn't set a concurrency group, but github actions doesn't
  # support conditional blocks of settings, so we use the SHA so the "group" is unique.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable

      - run: yarn format:check
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: yarn syncpack lint
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: yarn build

      - run: yarn test

      # This will fail on missing dist-file updates
      - name: Check for modified files
        uses: microsoft/beachball-actions/check-for-modified-files@cf7d34819ad50dce8894b3ff99a2a7899aefee3d # v3
        with:
          extraError: If files under "plugins/*/dist/" were changed, please run "yarn build" and commit the changes.
